import { describe, it, expect, beforeEach, vi } from 'vitest';
import { mount } from '@vue/test-utils';
import { createPinia, setActivePinia } from 'pinia';
import { createRouter, createMemoryHistory } from 'vue-router';
import i18next from 'i18next';
import I18NextVue from 'i18next-vue';
import { DateTime } from 'luxon';
import WeekView from '../week-view.vue';
import MonthView from '../month-view.vue';
import ListView from '../list-view.vue';
import EventCard from '@/site/components/event-card.vue';
import { usePublicCalendarStore } from '@/site/stores/publicCalendarStore';
import { useWidgetStore } from '../../stores/widgetStore';

// Initialize i18next for tests
i18next.init({
  lng: 'en',
  resources: {
    en: {
      system: {
        previous_week: 'Previous Week',
        next_week: 'Next Week',
        previous_month: 'Previous Month',
        next_month: 'Next Month',
        loading_events: 'Loading events...',
        no_events_with_filters: 'No events match your filters',
        no_events_available: 'No events available',
        no_events_this_month: 'No events this month',
      },
    },
  },
});

// Create a mock router
const createMockRouter = () => {
  return createRouter({
    history: createMemoryHistory(),
    routes: [
      { path: '/widget/:urlName', name: 'widget-calendar', component: { template: '<div></div>' } },
      { path: '/widget/:urlName/events/:eventId/:startTime(\\d{8}-\\d{4})?', name: 'widget-event-detail', component: { template: '<div></div>' } },
    ],
  });
};

describe('Widget View Components', () => {
  let router: any;

  beforeEach(() => {
    setActivePinia(createPinia());
    router = createMockRouter();
  });

  describe('WeekView', () => {
    it('renders week grid on desktop with 7 columns', async () => {
      const wrapper = mount(WeekView, {
        global: {
          plugins: [[I18NextVue, { i18next }], router],
        },
      });

      // Check for week grid container
      const weekGrid = wrapper.find('.week-grid');
      expect(weekGrid.exists()).toBe(true);

      // Week view should have 7 day columns
      const dayColumns = wrapper.findAll('.week-day-column');
      expect(dayColumns.length).toBe(7);
    });

    it('shows navigation controls for week', async () => {
      const wrapper = mount(WeekView, {
        global: {
          plugins: [[I18NextVue, { i18next }], router],
        },
      });

      // Should have previous and next buttons
      const prevButton = wrapper.find('.nav-prev');
      const nextButton = wrapper.find('.nav-next');

      expect(prevButton.exists()).toBe(true);
      expect(nextButton.exists()).toBe(true);
    });

    it('displays "+N more" indicator when more than 3 events per day', async () => {
      const publicStore = usePublicCalendarStore();

      // Use Luxon's local date so it matches the week grid keys generated by the component.
      // new Date().toISOString() returns UTC which can differ from the local date used by Luxon.
      const today = DateTime.now().toISODate()!;

      // Mock events with more than 3 events on one day
      // FIXED: Component uses publicStore.allEvents, not publicStore.events
      publicStore.allEvents = [
        { id: '1', start: { toLocal: () => ({ toISODate: () => today, toLocaleString: () => '10:00 AM' }) }, event: { id: 'e1', content: () => ({ name: 'Event 1' }), media: null, categories: [] } },
        { id: '2', start: { toLocal: () => ({ toISODate: () => today, toLocaleString: () => '11:00 AM' }) }, event: { id: 'e2', content: () => ({ name: 'Event 2' }), media: null, categories: [] } },
        { id: '3', start: { toLocal: () => ({ toISODate: () => today, toLocaleString: () => '12:00 PM' }) }, event: { id: 'e3', content: () => ({ name: 'Event 3' }), media: null, categories: [] } },
        { id: '4', start: { toLocal: () => ({ toISODate: () => today, toLocaleString: () => '1:00 PM' }) }, event: { id: 'e4', content: () => ({ name: 'Event 4' }), media: null, categories: [] } },
        { id: '5', start: { toLocal: () => ({ toISODate: () => today, toLocaleString: () => '2:00 PM' }) }, event: { id: 'e5', content: () => ({ name: 'Event 5' }), media: null, categories: [] } },
      ] as any;

      const wrapper = mount(WeekView, {
        global: {
          plugins: [[I18NextVue, { i18next }], router],
        },
      });

      // Should show overflow indicator
      const overflow = wrapper.find('.event-overflow');
      expect(overflow.exists()).toBe(true);
      expect(overflow.text()).toContain('+2');
    });
  });

  describe('MonthView', () => {
    it('renders traditional calendar grid on desktop', async () => {
      const wrapper = mount(MonthView, {
        global: {
          plugins: [[I18NextVue, { i18next }], router],
        },
      });

      // Check for month grid container (7x5 or 7x6)
      const monthGrid = wrapper.find('.month-grid');
      expect(monthGrid.exists()).toBe(true);

      // Month view should have day cells
      const dayCells = wrapper.findAll('.month-day-cell');
      expect(dayCells.length).toBeGreaterThanOrEqual(35); // At least 5 weeks
    });

    it('shows month navigation controls', async () => {
      const wrapper = mount(MonthView, {
        global: {
          plugins: [[I18NextVue, { i18next }], router],
        },
      });

      // Should have previous and next month buttons
      const prevButton = wrapper.find('.nav-prev');
      const nextButton = wrapper.find('.nav-next');

      expect(prevButton.exists()).toBe(true);
      expect(nextButton.exists()).toBe(true);
    });

    it('displays condensed list view on mobile', async () => {
      // FIXED: Mock window.innerWidth properly using vi.stubGlobal
      vi.stubGlobal('innerWidth', 400);

      // Mock window.addEventListener for resize listener
      const mockAddEventListener = vi.fn();
      vi.stubGlobal('addEventListener', mockAddEventListener);

      const wrapper = mount(MonthView, {
        global: {
          plugins: [[I18NextVue, { i18next }], router],
        },
      });

      // Wait for component to mount and check mobile state
      await wrapper.vm.$nextTick();

      // Should show condensed list instead of grid
      const condensedList = wrapper.find('.month-condensed-list');
      expect(condensedList.exists()).toBe(true);

      // Clean up mocks
      vi.unstubAllGlobals();
    });
  });

  describe('ListView', () => {
    // Build a minimal instance fixture compatible with both the day-grouping
    // getter (which calls instance.start.toLocal().toISODate()) and the
    // EventCard detailHref builder (which calls formatInstanceSlug, hitting
    // start.toUTC().toFormat(...)).
    const buildListInstance = (
      id: string,
      eventId: string,
      start: DateTime,
      dayKey: string,
    ) => ({
      id,
      start: {
        toLocal: () => ({
          toISODate: () => dayKey,
          toLocaleString: () => '10:00 AM',
        }),
        toUTC: () => start.toUTC(),
        toFormat: (fmt: string) => start.toUTC().toFormat(fmt),
      },
      end: null,
      isCancelled: false,
      event: {
        id: eventId,
        content: () => ({ name: `Event ${eventId}`, description: '' }),
        hasContent: () => true,
        getLanguages: () => ['en'],
        media: null,
        categories: [],
        location: null,
        isRecurring: false,
        isRepost: false,
        sourceCalendar: null,
      },
    });

    it('adapts calendar.vue pattern for widget by rendering an EventCard per instance', async () => {
      const publicStore = usePublicCalendarStore();
      const widgetStore = useWidgetStore();
      widgetStore.setCalendarUrlName('mycal');

      const start = DateTime.fromISO('2026-01-06T18:00:00.000Z', { zone: 'utc' });
      publicStore.allEvents = [
        buildListInstance('1', 'e1', start, '2026-01-06'),
      ] as any;

      const wrapper = mount(ListView, {
        global: {
          plugins: [[I18NextVue, { i18next }], router],
        },
      });

      // Should have a day section
      expect(wrapper.find('.day').exists()).toBe(true);

      // Should render exactly one EventCard for the single instance
      const eventCards = wrapper.findAllComponents(EventCard);
      expect(eventCards.length).toBe(1);
    });

    it('renders distinct EventCards with distinct detailHref props for two instances', async () => {
      const publicStore = usePublicCalendarStore();
      const widgetStore = useWidgetStore();
      widgetStore.setCalendarUrlName('mycal');

      const start1 = DateTime.fromISO('2026-01-06T18:00:00.000Z', { zone: 'utc' });
      const start2 = DateTime.fromISO('2026-01-07T19:00:00.000Z', { zone: 'utc' });
      publicStore.allEvents = [
        buildListInstance('1', 'e1', start1, '2026-01-06'),
        buildListInstance('2', 'e2', start2, '2026-01-07'),
      ] as any;

      const wrapper = mount(ListView, {
        global: {
          plugins: [[I18NextVue, { i18next }], router],
        },
      });

      const eventCards = wrapper.findAllComponents(EventCard);
      expect(eventCards.length).toBe(2);

      const href1 = eventCards[0].props('detailHref') as string;
      const href2 = eventCards[1].props('detailHref') as string;
      expect(href1).toBeTruthy();
      expect(href2).toBeTruthy();
      expect(href1).toContain('e1');
      expect(href2).toContain('e2');
      expect(href1).not.toBe(href2);
    });
  });

  describe('openEvent slug navigation', () => {
    const today = DateTime.now().toISODate()!;
    // A known instant so we can assert the exact slug. 2026-05-08 18:00 UTC.
    const fixedStart = DateTime.fromISO('2026-05-08T18:00:00.000Z', { zone: 'utc' });
    const fixedSlug = '20260508-1800';

    const buildInstance = (start: DateTime) => ({
      id: 'inst-1',
      start: {
        // toLocal used by component grouping for dayKey
        toLocal: () => ({
          toISODate: () => today,
          toLocaleString: () => '10:00 AM',
        }),
        // toUTC used by formatInstanceSlug
        toUTC: () => start.toUTC(),
        // Luxon passthrough fields needed by formatInstanceSlug
        toFormat: (fmt: string) => start.toUTC().toFormat(fmt),
      },
      end: null,
      isCancelled: false,
      event: {
        id: 'evt-1',
        content: () => ({ name: 'Test Event', description: '' }),
        // EventCard uses useLocalizedContent → hasContent / getLanguages
        hasContent: () => true,
        getLanguages: () => ['en'],
        media: null,
        categories: [],
        location: null,
        isRecurring: false,
        isRepost: false,
        sourceCalendar: null,
      },
    });

    it('WeekView openEvent pushes route params including startTime slug', async () => {
      const publicStore = usePublicCalendarStore();
      const widgetStore = useWidgetStore();
      widgetStore.setCalendarUrlName('mycal');

      publicStore.allEvents = [buildInstance(fixedStart)] as any;

      const pushSpy = vi.spyOn(router, 'push');

      const wrapper = mount(WeekView, {
        global: {
          plugins: [[I18NextVue, { i18next }], router],
        },
      });

      const eventEl = wrapper.find('.event-item');
      expect(eventEl.exists()).toBe(true);
      await eventEl.trigger('click');

      expect(pushSpy).toHaveBeenCalledWith({
        name: 'widget-event-detail',
        params: {
          urlName: 'mycal',
          eventId: 'evt-1',
          startTime: fixedSlug,
        },
      });
    });

    it('MonthView openEvent pushes route params including startTime slug', async () => {
      const publicStore = usePublicCalendarStore();
      const widgetStore = useWidgetStore();
      widgetStore.setCalendarUrlName('mycal');

      publicStore.allEvents = [buildInstance(fixedStart)] as any;

      const pushSpy = vi.spyOn(router, 'push');

      const wrapper = mount(MonthView, {
        global: {
          plugins: [[I18NextVue, { i18next }], router],
        },
      });

      const eventEl = wrapper.find('.event-preview');
      expect(eventEl.exists()).toBe(true);
      await eventEl.trigger('click');

      expect(pushSpy).toHaveBeenCalledWith({
        name: 'widget-event-detail',
        params: {
          urlName: 'mycal',
          eventId: 'evt-1',
          startTime: fixedSlug,
        },
      });
    });

    it('ListView EventCard detailHref includes the startTime slug', async () => {
      const publicStore = usePublicCalendarStore();
      const widgetStore = useWidgetStore();
      widgetStore.setCalendarUrlName('mycal');

      publicStore.allEvents = [buildInstance(fixedStart)] as any;

      const wrapper = mount(ListView, {
        global: {
          plugins: [[I18NextVue, { i18next }], router],
        },
      });

      const cards = wrapper.findAllComponents(EventCard);
      expect(cards.length).toBe(1);
      const detailHref = cards[0].props('detailHref') as string;
      expect(detailHref).toContain(fixedSlug);
      expect(detailHref).toContain('mycal');
      expect(detailHref).toContain('evt-1');
    });
  });

  describe('Navigation and Gestures', () => {
    it('handles swipe left gesture for next week', async () => {
      const wrapper = mount(WeekView, {
        global: {
          plugins: [[I18NextVue, { i18next }], router],
        },
      });

      // Swipe gestures tested in isolation (composable handles logic)
      const weekContainer = wrapper.find('.week-view');
      expect(weekContainer.exists()).toBe(true);
    });

    it('handles swipe right gesture for previous week', async () => {
      const wrapper = mount(WeekView, {
        global: {
          plugins: [[I18NextVue, { i18next }], router],
        },
      });

      // Swipe gestures tested in isolation (composable handles logic)
      const weekContainer = wrapper.find('.week-view');
      expect(weekContainer.exists()).toBe(true);
    });
  });
});
