import { Sequelize } from 'sequelize';

/**
 * Alter the events.space_id foreign key to ON DELETE SET NULL.
 *
 * Migration 0032 created the FK without an explicit ON DELETE clause, so the
 * database falls back to NO ACTION (Postgres) / RESTRICT-like semantics. The
 * Place + Spaces atomic-save model (pv-0pht) treats Space deletion as the
 * trigger for whole-venue fallback: when an owner removes a Space inside the
 * Place save, any events still pointing at it should fall back to the parent
 * Place rather than block the transaction. Surfacing that semantic through
 * the FK lets the LocationService nest the Space delete inside the same
 * transaction as the Place upsert without enumerating referencing events.
 *
 * Dialect handling:
 * - Postgres: drop and re-add the constraint via raw SQL (the existing
 *   constraint name varies by Sequelize version and historical schema, so we
 *   look it up dynamically against pg_catalog).
 * - SQLite: ALTER TABLE cannot modify FK behavior. The integration-test path
 *   relies on `db.sync({ force: true })` which reads the entity decorator
 *   directly, so the migration is a no-op on SQLite. The migration runner
 *   test for FK behavior on SQLite enables `PRAGMA foreign_keys = ON` and
 *   asserts behavior against the table schema produced by 0032 as amended
 *   here at the entity layer; see commentary on the entity decorator in
 *   src/server/calendar/entity/event.ts.
 *
 * Bead: pv-0pht.2.
 */
export default {
  async up({ context: sequelize }: { context: Sequelize }) {
    const dialect = sequelize.getDialect();

    if (dialect === 'postgres') {
      // Look up the existing FK constraint name on event.space_id. Sequelize
      // uses an autogenerated name like `event_space_id_fkey` but we resolve
      // dynamically to stay robust against schema-history variation.
      const [rows] = await sequelize.query(`
        SELECT conname
        FROM pg_constraint c
        JOIN pg_class cls ON c.conrelid = cls.oid
        JOIN pg_attribute a ON a.attrelid = cls.oid AND a.attnum = ANY (c.conkey)
        WHERE cls.relname = 'event'
          AND c.contype = 'f'
          AND a.attname = 'space_id';
      `) as [Array<{ conname: string }>, unknown];

      for (const row of rows) {
        await sequelize.query(`ALTER TABLE "event" DROP CONSTRAINT "${row.conname}";`);
      }

      await sequelize.query(`
        ALTER TABLE "event"
        ADD CONSTRAINT "event_space_id_fkey"
        FOREIGN KEY ("space_id") REFERENCES "location_space" ("id")
        ON DELETE SET NULL;
      `);
    }
    // SQLite: see header comment. Test path uses entity-driven schema sync.
  },

  async down({ context: sequelize }: { context: Sequelize }) {
    const dialect = sequelize.getDialect();

    if (dialect === 'postgres') {
      const [rows] = await sequelize.query(`
        SELECT conname
        FROM pg_constraint c
        JOIN pg_class cls ON c.conrelid = cls.oid
        JOIN pg_attribute a ON a.attrelid = cls.oid AND a.attnum = ANY (c.conkey)
        WHERE cls.relname = 'event'
          AND c.contype = 'f'
          AND a.attname = 'space_id';
      `) as [Array<{ conname: string }>, unknown];

      for (const row of rows) {
        await sequelize.query(`ALTER TABLE "event" DROP CONSTRAINT "${row.conname}";`);
      }

      // Restore the pre-0034 constraint shape: FK without ON DELETE behavior
      // (Postgres default NO ACTION).
      await sequelize.query(`
        ALTER TABLE "event"
        ADD CONSTRAINT "event_space_id_fkey"
        FOREIGN KEY ("space_id") REFERENCES "location_space" ("id");
      `);
    }
  },
};
