import config from 'config';

/**
 * Validates that production-required secrets are properly configured.
 *
 * In production mode (NODE_ENV=production), development-default secrets
 * must be replaced with cryptographically secure values generated by bin/deploy.sh.
 *
 * @throws Error if development-default secrets are used in production
 */
export function validateProductionSecrets(): void {
  const jwtSecret = config.get<string>('jwt.secret');
  const sessionSecret = config.get<string>('session.secret');
  const emailHashSecret = config.get<string>('moderation.emailHashSecret');
  const encryptionKey = config.get<string>('funding.encryptionKey');
  const dbPassword = config.has('database.password') ? config.get<string>('database.password') : '';
  const importHmacSecret = config.has('calendar.import.hmacSecret')
    ? config.get<string>('calendar.import.hmacSecret')
    : '';

  if (!dbPassword) {
    throw new Error(
      'DB_PASSWORD must be set in production. Run bin/deploy.sh to generate secure secrets, ' +
      'or set the DB_PASSWORD environment variable to a cryptographically secure value.',
    );
  }

  if (jwtSecret.includes('development-only')) {
    throw new Error(
      'JWT_SECRET must be set in production. Run bin/deploy.sh to generate secure secrets, ' +
      'or set the JWT_SECRET environment variable to a cryptographically secure value.',
    );
  }

  if (sessionSecret.includes('development-only')) {
    throw new Error(
      'SESSION_SECRET must be set in production. Run bin/deploy.sh to generate secure secrets, ' +
      'or set the SESSION_SECRET environment variable to a cryptographically secure value.',
    );
  }

  if (emailHashSecret.includes('development-only')) {
    throw new Error(
      'EMAIL_HASH_SECRET must be set in production. Run bin/deploy.sh to generate secure secrets, ' +
      'or set the EMAIL_HASH_SECRET environment variable to a cryptographically secure value.',
    );
  }

  if (encryptionKey.includes('development-only')) {
    throw new Error(
      'ENCRYPTION_KEY must be set in production. Run bin/deploy.sh to generate secure secrets, ' +
      'or set the ENCRYPTION_KEY environment variable to a cryptographically secure value.',
    );
  }

  if (!importHmacSecret || importHmacSecret.includes('development-only')) {
    throw new Error(
      'CALENDAR_IMPORT_HMAC_SECRET must be set in production. Generate using: openssl rand -base64 32, ' +
      'or set the CALENDAR_IMPORT_HMAC_SECRET environment variable to a cryptographically secure value.',
    );
  }
}
