import config from 'config';

/**
 * Validates that production-required secrets are properly configured.
 *
 * In production mode (NODE_ENV=production), development-default secrets
 * must be replaced with cryptographically secure values generated by bin/setup.sh.
 *
 * @throws Error if development-default secrets are used in production
 */
export function validateProductionSecrets(): void {
  const jwtSecret = config.get<string>('jwt.secret');
  const sessionSecret = config.get<string>('session.secret');

  if (jwtSecret.includes('development-only')) {
    throw new Error(
      'JWT_SECRET must be set in production. Run bin/setup.sh to generate secure secrets, ' +
      'or set the JWT_SECRET environment variable to a cryptographically secure value.',
    );
  }

  if (sessionSecret.includes('development-only')) {
    throw new Error(
      'SESSION_SECRET must be set in production. Run bin/setup.sh to generate secure secrets, ' +
      'or set the SESSION_SECRET environment variable to a cryptographically secure value.',
    );
  }
}
